Added Mesh with Commerce and Catalog Sources
adobe/adobe-commerce-samples pull request #14
Opened 2024-06-06 15:55 UTC by revanth0212

## Description

Added a mesh sample to use Commerce and Catalog services through API Mesh.

## Related Issue

NA

## Motivation and Context

Enable customers to use Commerce and Catalog Services through API Mesh.

## How Has This Been Tested?

Deployed on API Mesh and Mesh @ Edge

```
Mesh ID: 18205ff7-6701-451b-916e-36372101e2fc
Mesh Endpoint: https://graph.adobe.io/api/18205ff7-6701-451b-916e-36372101e2fc/graphql?api_key=469b137a4640492bbb8967cd9b2bce29
Edge Mesh Endpoint: https://edge-sandbox-graph.adobe.io/api/18205ff7-6701-451b-916e-36372101e2fc/graphql
```

Sample Query:

```graphql
{
  products(skus: ["24-WG080"]) {
    attributes {
        name
        value
    }
    ... on ComplexProductView {
      options {
        title
        values {
          ... on ProductViewOptionValueProduct {
            product {
              sku
              name
              price {
                final {
                  amount {
                    value
                    currency
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

## Screenshots (if appropriate):

![image](https://github.com/adobe/adobe-commerce-samples/assets/35203638/00c3553e-74df-4c7a-b795-ce62b75b34c3)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-06-06 21:12 UTC, slamech commented on api-mesh/commerce-and-catalog/README.md
Are there any pre-requisites for this? Also can we add in the link to the catalog service documentation here? - https://developer.adobe.com/commerce/services/graphql/catalog-service/

2024-06-06 21:14 UTC, slamech commented on api-mesh/commerce-and-catalog/meshConfig.json
We need to add comments in the mesh config to explain what each section is doing. We should also remove these endpoints and leave placeholders for developers to use their services.

2024-06-06 21:16 UTC, slamech requested changes
Left some comments in there. Primarily need to add in any prerequisites, and add comments to the configurations so they are self-explanatory.

2024-06-13 18:50 UTC, revanth0212 commented on api-mesh/commerce-and-catalog/meshConfig.json
Sure Surya. Ill add comments. Regarding the URLs I was following the existing sample meshes and they seemed to have URLs. Also, the URLs used in this mesh are the ones being used in the [Commerce dropins boilerplate](https://github.com/hlxsites/boilerplate-commerce-dropins).

I can remove the URLs but I thought it would be easy for people to get started with less friction if they have a sample that works OOB. Please let me know 🙏

2024-06-14 16:22 UTC, juan-ayala commented on api-mesh/commerce-and-catalog/meshConfig.json
FWIT, I found the commerce URLs in there helpful during the Partner Day event. Having that reference endpoint saved me from having to create a mock. Also helped getting the boilerplate project up and running.

2024-06-18 14:43 UTC, revanth0212 commented on api-mesh/commerce-and-catalog/meshConfig.json
Thank you @juan-ayala . Glad they were helpful 🙏 

We have decided to have the URLs around but in the `.env` file instead. Just a minor change.

2024-06-26 00:52 UTC, slamech approved these changes

2024-06-26 00:52 UTC, merged